npm install netlify-cli -g
netlify functions:create
/.netlify/functions/FUNCTION-awdev-netlify
[build]
  command = "yarn build"
  publish = ".awdev"

[build.environment]
  JAMIFY_NEXT_ISR = "false"
  JAMIFY_NEXT_FEATURE_IMAGES = "false"
  JAMIFY_NEXT_INLINE_IMAGES = "false"
